USE [master]
GO

/****** Object:  Database [Autoboy]    Script Date: 9/29/2014 8:08:28 PM ******/
CREATE DATABASE [Autoboy]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Autoboy', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS2012\MSSQL\DATA\Autoboy.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Autoboy_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS2012\MSSQL\DATA\Autoboy_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Autoboy] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Autoboy].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Autoboy] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Autoboy] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Autoboy] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Autoboy] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Autoboy] SET ARITHABORT OFF 
GO

ALTER DATABASE [Autoboy] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Autoboy] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Autoboy] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Autoboy] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Autoboy] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Autoboy] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Autoboy] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Autoboy] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Autoboy] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Autoboy] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Autoboy] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Autoboy] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Autoboy] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Autoboy] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Autoboy] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Autoboy] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Autoboy] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Autoboy] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Autoboy] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Autoboy] SET  MULTI_USER 
GO

ALTER DATABASE [Autoboy] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Autoboy] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Autoboy] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Autoboy] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Autoboy] SET  READ_WRITE 
GO


